// <auto-generated />
using Clientes.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Clientes.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.20");

            modelBuilder.Entity("Clientes.Models.Cliente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ApellidoMaterno")
                        .HasColumnType("TEXT");

                    b.Property<string>("ApellidoPaterno")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Telefono")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Clientes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ApellidoMaterno = "Hernández",
                            ApellidoPaterno = "Gómez",
                            Nombre = "Ana",
                            Telefono = "5551234567"
                        },
                        new
                        {
                            Id = 2,
                            ApellidoMaterno = "Ortiz",
                            ApellidoPaterno = "Pérez",
                            Nombre = "Luis",
                            Telefono = "5552345678"
                        },
                        new
                        {
                            Id = 3,
                            ApellidoMaterno = "Sánchez",
                            ApellidoPaterno = "López",
                            Nombre = "María",
                            Telefono = "5553456789"
                        },
                        new
                        {
                            Id = 4,
                            ApellidoMaterno = "Morales",
                            ApellidoPaterno = "Ramírez",
                            Nombre = "Carlos",
                            Telefono = "5554567890"
                        },
                        new
                        {
                            Id = 5,
                            ApellidoMaterno = "Díaz",
                            ApellidoPaterno = "Torres",
                            Nombre = "Sofía",
                            Telefono = "5555678901"
                        });
                });

            modelBuilder.Entity("Clientes.Models.Producto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Descripcion")
                        .HasColumnType("TEXT");

                    b.Property<int>("Existencia")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Precio")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Productos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Descripcion = "Bolsa de 1kg de manzanas frescas",
                            Existencia = 30,
                            Nombre = "Manzanas Rojas",
                            Precio = 45.00m
                        },
                        new
                        {
                            Id = 2,
                            Descripcion = "Paquete de 900g",
                            Existencia = 50,
                            Nombre = "Arroz Integral",
                            Precio = 28.50m
                        },
                        new
                        {
                            Id = 3,
                            Descripcion = "Botella de 1L",
                            Existencia = 100,
                            Nombre = "Leche Entera",
                            Precio = 22.00m
                        },
                        new
                        {
                            Id = 4,
                            Descripcion = "Paquete con 10 rebanadas",
                            Existencia = 25,
                            Nombre = "Pan Integral",
                            Precio = 38.00m
                        },
                        new
                        {
                            Id = 5,
                            Descripcion = "Docena de huevos",
                            Existencia = 40,
                            Nombre = "Huevos Orgánicos",
                            Precio = 52.00m
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
